CREATE TABLE `GE_CUSTOMER` (
  `ID` bigint(20) NOT NULL,
  `USER_NAME` varchar(255) DEFAULT '',
  `REAL_NAME` varchar(255) NOT NULL DEFAULT '',
  `TEL` varchar(25) NOT NULL DEFAULT '',
  `PASSWORD` varchar(255) NOT NULL DEFAULT '',
  `TOTAL` decimal(19,5) NOT NULL DEFAULT '0.00000',
  `EMAIL` varchar(50) DEFAULT NULL,
  `SOURCE_CUSTOMER` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SOURCE_CUSTOMER_FK` (`SOURCE_CUSTOMER`),
  CONSTRAINT `SOURCE_CUSTOMER_FK` FOREIGN KEY (`SOURCE_CUSTOMER`) REFERENCES `GE_CUSTOMER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;